;;; ewwm-qutebrowser-theme.el --- Theme sync for qutebrowser  -*- lexical-binding: t -*-

;; Copyright (C) 2026 Free Software Foundation, Inc.

;;; Commentary:
;; Synchronize Emacs theme colors to qutebrowser.  Extracts face
;; colors from the current Emacs theme and writes a Python config
;; file that qutebrowser sources for consistent color theming.

;;; Code:

(require 'cl-lib)
(require 'ewwm-core)

(declare-function ewwm-qutebrowser-ipc-send
                  "ewwm-qutebrowser-ipc")

;; ── Customization ────────────────────────────────────────────

(defgroup ewwm-qutebrowser-theme nil
  "Theme synchronization for qutebrowser."
  :group 'ewwm-qutebrowser
  :prefix "ewwm-qutebrowser-theme-")

(defcustom ewwm-qutebrowser-theme-auto-sync t
  "Non-nil to enable automatic theme synchronization."
  :type 'boolean
  :group 'ewwm-qutebrowser-theme)

(defcustom ewwm-qutebrowser-theme-file
  "~/.config/qutebrowser/exwm-vr-theme.py"
  "Path to the generated qutebrowser theme Python file."
  :type 'string
  :group 'ewwm-qutebrowser-theme)

(defcustom ewwm-qutebrowser-theme-extra-css nil
  "Extra CSS to inject into qutebrowser web pages.
Appended to the content.user_stylesheets setting."
  :type '(choice (const nil) string)
  :group 'ewwm-qutebrowser-theme)

;; ── Color extraction ─────────────────────────────────────────

(defun ewwm-qutebrowser-theme--face-color (face attr)
  "Get color ATTR from FACE, falling back to default.
ATTR is :foreground or :background."
  (let ((val (face-attribute face attr nil t)))
    (if (and val (stringp val) (not (string= val "unspecified")))
        val
      (let ((def (face-attribute 'default attr nil t)))
        (if (and def (stringp def)
                 (not (string= def "unspecified")))
            def
          (if (eq attr :background) "#1a1a2e" "#e0e0e0"))))))

(defun ewwm-qutebrowser-theme--extract-colors ()
  "Extract face colors from the current Emacs theme.
Return an alist of (NAME . \"#hex\") pairs for: bg, fg,
modeline-bg, modeline-fg, highlight, region, comment,
string, keyword, error, success, warning."
  (list
   (cons "bg" (ewwm-qutebrowser-theme--face-color
               'default :background))
   (cons "fg" (ewwm-qutebrowser-theme--face-color
               'default :foreground))
   (cons "modeline-bg" (ewwm-qutebrowser-theme--face-color
                        'mode-line :background))
   (cons "modeline-fg" (ewwm-qutebrowser-theme--face-color
                        'mode-line :foreground))
   (cons "highlight" (ewwm-qutebrowser-theme--face-color
                      'highlight :background))
   (cons "region" (ewwm-qutebrowser-theme--face-color
                   'region :background))
   (cons "comment" (ewwm-qutebrowser-theme--face-color
                    'font-lock-comment-face :foreground))
   (cons "string" (ewwm-qutebrowser-theme--face-color
                   'font-lock-string-face :foreground))
   (cons "keyword" (ewwm-qutebrowser-theme--face-color
                    'font-lock-keyword-face :foreground))
   (cons "error" (ewwm-qutebrowser-theme--face-color
                  'error :foreground))
   (cons "success" (ewwm-qutebrowser-theme--face-color
                    'success :foreground))
   (cons "warning" (ewwm-qutebrowser-theme--face-color
                    'warning :foreground))))

;; ── Python config generation ─────────────────────────────────

(defun ewwm-qutebrowser-theme--generate-python (colors)
  "Generate Python config string from COLORS alist.
Maps extracted colors to qutebrowser c.colors.* settings."
  (let ((bg  (alist-get "bg" colors nil nil #'string=))
        (fg  (alist-get "fg" colors nil nil #'string=))
        (ml-bg (alist-get "modeline-bg" colors
                          nil nil #'string=))
        (ml-fg (alist-get "modeline-fg" colors
                          nil nil #'string=))
        (hl  (alist-get "highlight" colors nil nil #'string=))
        (rg  (alist-get "region" colors nil nil #'string=))
        (kw  (alist-get "keyword" colors nil nil #'string=))
        (err (alist-get "error" colors nil nil #'string=))
        (wrn (alist-get "warning" colors nil nil #'string=)))
    (concat
     "# Auto-generated by ewwm-qutebrowser-theme.el\n"
     "# Do not edit manually.\n\n"
     (format "c.colors.completion.fg = '%s'\n" fg)
     (format "c.colors.completion.odd.bg = '%s'\n" bg)
     (format "c.colors.completion.even.bg = '%s'\n" bg)
     (format "c.colors.completion.category.fg = '%s'\n" kw)
     (format "c.colors.completion.category.bg = '%s'\n" bg)
     (format "c.colors.completion.item.selected.fg = '%s'\n"
             fg)
     (format "c.colors.completion.item.selected.bg = '%s'\n"
             rg)
     (format "c.colors.completion.match.fg = '%s'\n" hl)
     (format "c.colors.statusbar.normal.fg = '%s'\n" ml-fg)
     (format "c.colors.statusbar.normal.bg = '%s'\n" ml-bg)
     (format "c.colors.statusbar.command.fg = '%s'\n" fg)
     (format "c.colors.statusbar.command.bg = '%s'\n" bg)
     (format "c.colors.tabs.bar.bg = '%s'\n" bg)
     (format "c.colors.tabs.odd.fg = '%s'\n" fg)
     (format "c.colors.tabs.odd.bg = '%s'\n" bg)
     (format "c.colors.tabs.even.fg = '%s'\n" fg)
     (format "c.colors.tabs.even.bg = '%s'\n" bg)
     (format "c.colors.tabs.selected.odd.fg = '%s'\n" ml-fg)
     (format "c.colors.tabs.selected.odd.bg = '%s'\n" ml-bg)
     (format "c.colors.tabs.selected.even.fg = '%s'\n" ml-fg)
     (format "c.colors.tabs.selected.even.bg = '%s'\n" ml-bg)
     (format "c.colors.hints.fg = '%s'\n" bg)
     (format "c.colors.hints.bg = '%s'\n" kw)
     (format "c.colors.messages.error.fg = '%s'\n" fg)
     (format "c.colors.messages.error.bg = '%s'\n" err)
     (format "c.colors.messages.warning.fg = '%s'\n" fg)
     (format "c.colors.messages.warning.bg = '%s'\n" wrn)
     (if ewwm-qutebrowser-theme-extra-css
         (format "\nc.content.user_stylesheets = ['%s']\n"
                 ewwm-qutebrowser-theme-extra-css)
       ""))))

;; ── Sync command ─────────────────────────────────────────────

(defun ewwm-qutebrowser-theme-sync ()
  "Extract Emacs theme colors and write qutebrowser config.
Writes Python to `ewwm-qutebrowser-theme-file' and sends
:config-source to qutebrowser via IPC."
  (interactive)
  (let* ((colors (ewwm-qutebrowser-theme--extract-colors))
         (python (ewwm-qutebrowser-theme--generate-python
                  colors))
         (path (expand-file-name
                ewwm-qutebrowser-theme-file)))
    (make-directory (file-name-directory path) t)
    (with-temp-file path
      (insert python))
    (when (fboundp 'ewwm-qutebrowser-ipc-send)
      (ewwm-qutebrowser-ipc-send
       (format ":config-source %s" path)))
    (message "ewwm-qutebrowser-theme: synced to %s" path)))

;; ── Hook management ──────────────────────────────────────────

(defun ewwm-qutebrowser-theme--on-theme-change (&rest _args)
  "Hook function for theme change hooks.
Syncs when `ewwm-qutebrowser-theme-auto-sync' is non-nil.
Accepts optional _ARGS for `enable-theme-functions' compat."
  (when ewwm-qutebrowser-theme-auto-sync
    (ewwm-qutebrowser-theme-sync)))

(defun ewwm-qutebrowser-theme-enable ()
  "Enable automatic theme sync on Emacs theme changes."
  (interactive)
  (setq ewwm-qutebrowser-theme-auto-sync t)
  (add-hook 'enable-theme-functions
            #'ewwm-qutebrowser-theme--on-theme-change)
  (message "ewwm-qutebrowser-theme: auto-sync enabled"))

(defun ewwm-qutebrowser-theme-disable ()
  "Disable automatic theme sync on Emacs theme changes."
  (interactive)
  (setq ewwm-qutebrowser-theme-auto-sync nil)
  (remove-hook 'enable-theme-functions
               #'ewwm-qutebrowser-theme--on-theme-change)
  (message "ewwm-qutebrowser-theme: auto-sync disabled"))

(provide 'ewwm-qutebrowser-theme)
;;; ewwm-qutebrowser-theme.el ends here
