{ config, lib, pkgs, ... }:

let
  cfg = config.programs.exwm-vr;

  # Convert a Nix attrset to Elisp setq expressions
  nixToElisp = attrs:
    let
      convert = name: value:
        let
          elispName = builtins.replaceStrings [ "_" ] [ "-" ] name;
          elispValue =
            if builtins.isBool value then (if value then "t" else "nil")
            else if builtins.isInt value then toString value
            else if builtins.isFloat value then toString value
            else if builtins.isString value then ''"${value}"''
            else if builtins.isList value then
              "'(${builtins.concatStringsSep " " (map (v:
                if builtins.isString v then ''"${v}"''
                else toString v
              ) value)})"
            else throw "Unsupported type for Elisp conversion: ${name}";
        in
        "(setq ${elispName} ${elispValue})";
    in
    builtins.concatStringsSep "\n" (lib.mapAttrsToList convert attrs);

  # Generate Qutebrowser theme from Emacs theme name
  qutebrowserTheme = theme:
    let
      themes = {
        "modus-vivendi" = {
          bg = "#000000";
          fg = "#ffffff";
          accent = "#79a8ff";
          sel-bg = "#3f3f3f";
          sel-fg = "#ffffff";
          warn = "#fec43f";
          error = "#ff5f59";
        };
        "modus-operandi" = {
          bg = "#ffffff";
          fg = "#000000";
          accent = "#0031a9";
          sel-bg = "#c4c4c4";
          sel-fg = "#000000";
          warn = "#813e00";
          error = "#a60000";
        };
        "ef-autumn" = {
          bg = "#0f0e06";
          fg = "#cfbcba";
          accent = "#efa040";
          sel-bg = "#3a2a0a";
          sel-fg = "#cfbcba";
          warn = "#d0a020";
          error = "#ff7a5f";
        };
      };
      colors = themes.${theme} or themes."modus-vivendi";
    in ''
      # EXWM-VR Qutebrowser theme — generated from Emacs theme: ${theme}
      # Do not edit manually; managed by home-manager.

      c.colors.completion.fg = "${colors.fg}"
      c.colors.completion.odd.bg = "${colors.bg}"
      c.colors.completion.even.bg = "${colors.bg}"
      c.colors.completion.category.fg = "${colors.accent}"
      c.colors.completion.category.bg = "${colors.bg}"
      c.colors.completion.item.selected.fg = "${colors.sel-fg}"
      c.colors.completion.item.selected.bg = "${colors.sel-bg}"
      c.colors.statusbar.normal.fg = "${colors.fg}"
      c.colors.statusbar.normal.bg = "${colors.bg}"
      c.colors.statusbar.command.fg = "${colors.fg}"
      c.colors.statusbar.command.bg = "${colors.bg}"
      c.colors.tabs.bar.bg = "${colors.bg}"
      c.colors.tabs.odd.fg = "${colors.fg}"
      c.colors.tabs.odd.bg = "${colors.bg}"
      c.colors.tabs.even.fg = "${colors.fg}"
      c.colors.tabs.even.bg = "${colors.bg}"
      c.colors.tabs.selected.odd.fg = "${colors.sel-fg}"
      c.colors.tabs.selected.odd.bg = "${colors.sel-bg}"
      c.colors.tabs.selected.even.fg = "${colors.sel-fg}"
      c.colors.tabs.selected.even.bg = "${colors.sel-bg}"
      c.colors.hints.fg = "${colors.bg}"
      c.colors.hints.bg = "${colors.accent}"
      c.colors.messages.error.fg = "${colors.fg}"
      c.colors.messages.error.bg = "${colors.error}"
      c.colors.messages.warning.fg = "${colors.fg}"
      c.colors.messages.warning.bg = "${colors.warn}"
    '';

  configEl = ''
    ;;; exwm-vr-config.el --- Generated EXWM-VR configuration  -*- lexical-binding: t; -*-
    ;; Generated by home-manager. Do not edit manually.

    ${nixToElisp cfg.config}

    ${lib.optionalString cfg.keepassxc.enable ''
    (setq ewwm-keepassxc-enable t)
    (setq ewwm-keepassxc-database-path "${cfg.keepassxc.databasePath}")
    ''}

    ${lib.optionalString (cfg.winkCalibration != null) ''
    (setq ewwm-vr-wink-calibration-file "${cfg.winkCalibration}")
    ''}

    (setq ewwm-vr-gaze-zone-layout "${cfg.gazeZoneLayout}")

    (provide 'exwm-vr-config)
    ;;; exwm-vr-config.el ends here
  '';

in {
  options.programs.exwm-vr = {
    enable = lib.mkEnableOption "EXWM-VR user configuration";

    config = lib.mkOption {
      type = lib.types.attrsOf (lib.types.oneOf [
        lib.types.bool
        lib.types.int
        lib.types.float
        lib.types.str
        (lib.types.listOf lib.types.str)
      ]);
      default = { };
      description = ''
        Attribute set of EXWM-VR configuration variables.
        Keys are converted from snake_case to kebab-case for Elisp.
        Values are converted: bool -> t/nil, string -> "string", int -> int.
        Generates setq forms in ~/.config/exwm-vr/config.el.
      '';
      example = lib.literalExpression ''
        {
          ewwm_floating_border_width = 2;
          ewwm_workspace_number = 4;
          ewwm_vr_enable = true;
        }
      '';
    };

    winkCalibration = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Path to wink calibration JSON file.";
    };

    gazeZoneLayout = lib.mkOption {
      type = lib.types.enum [ "default" "compact" "wide" "minimal" ];
      default = "default";
      description = "Gaze zone layout preset.";
    };

    keepassxc = {
      enable = lib.mkEnableOption "KeePassXC integration";
      databasePath = lib.mkOption {
        type = lib.types.str;
        default = "~/Passwords.kdbx";
        description = "Path to KeePassXC database file.";
      };
    };

    theme = lib.mkOption {
      type = lib.types.enum [ "modus-vivendi" "modus-operandi" "ef-autumn" ];
      default = "modus-vivendi";
      description = ''
        Emacs theme name. Also generates a matching Qutebrowser color scheme.
      '';
    };

    configDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.xdg.configHome}/exwm-vr";
      description = "EXWM-VR configuration directory.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Generate config.el from Nix attrset
    xdg.configFile."exwm-vr/config.el".text = configEl;

    # Generate Qutebrowser theme
    xdg.configFile."qutebrowser/exwm-vr-theme.py".text = qutebrowserTheme cfg.theme;

    # Set environment variable pointing to config dir
    home.sessionVariables = {
      EXWM_VR_CONFIG_DIR = cfg.configDir;
    };
  };
}
